　
          <li>
            <div class="citem"> <a href="[field:arcurl/]" title="[field:title/]"> <img src="[field:picname/]" style="width: 280px;height: 180px" class="attachment-post-thumbnail wp-post-image" alt="[field:title/]" /><span></span> </a>
              <div class="citemtxt"> <a href="[field:arcurl/]" title="[field:title/]">
                <h4>[field:title/]</h4>
                </a>
                <p><span><a href='[field:typeurl/]'>[field:typename/]</a></span><em>
                  <label><script src="[field:phpurl/]/count.php?view=yes&aid=[field:id/]&mid=[field:mid/]" type='text/javascript' language="javascript"></script></label>
                  浏览</em> <!-- .comments-link --> 
                </p>
              </div>
            </div>
          </li>