<?php
$z[0]=Array("arcurl","",62,77);
$z[1]=Array("title","",86,100);
$z[2]=Array("picname","",113,129);
$z[3]=Array("title","",219,233);
$z[4]=Array("arcurl","",303,318);
$z[5]=Array("title","",327,341);
$z[6]=Array("title","",365,379);
$z[7]=Array("typeurl","",442,458);
$z[8]=Array("typename","",460,477);
$z[9]=Array("phpurl","",532,547);
$z[10]=Array("id","",571,582);
$z[11]=Array("mid","",587,599);

?>