<?php
$z[0]=Array("field","",79,98);
$z[0][4]['name']="title";
$z[1]=Array("global","",99,125);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",166,188);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",228,279);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",696,731);
$z[4][4]['filename']="head.htm";
$z[5]=Array("prenext","",909,937);
$z[5][4]['get']="preurl";
$z[6]=Array("prenext","",964,993);
$z[6][4]['get']="nexturl";
$z[7]=Array("field","",1029,1048);
$z[7][4]['name']="title";
$z[8]=Array("field","",1307,1325);
$z[8][4]['name']="body";
$z[9]=Array("field","",1532,1588);
$z[9][4]['name']="pubdate";
$z[9][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[10]=Array("field","",1640,1667);
$z[10][4]['name']="phpurl";
$z[11]=Array("field","",1691,1714);
$z[11][4]['name']="id";
$z[12]=Array("field","",1719,1743);
$z[12][4]['name']="mid";
$z[13]=Array("arclist","　\r\n          <li>\r\n            <div class=\"citem\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"> <img src=\"[field:picname/]\" style=\"width: 280px;height: 180px\" class=\"attachment-post-thumbnail wp-post-image\" alt=\"[field:title/]\" /><span></span> </a>\r\n              <div class=\"citemtxt\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n                <h4>[field:title/]</h4>\r\n                </a>\r\n                <p><span><a href='[field:typeurl/]'>[field:typename/]</a></span><em>\r\n                  <label><script src=\"[field:phpurl/]/count.php?view=yes&aid=[field:id/]&mid=[field:mid/]\" type='text/javascript' language=\"javascript\"></script></label>\r\n                  浏览</em> <!-- .comments-link --> \r\n                </p>\r\n              </div>\r\n            </div>\r\n          </li>\r\n          ",2213,3083);
$z[13][4]['typeid']="1";
$z[13][4]['row']="8";
$z[13][4]['titlelen']="32";
$z[14]=Array("include","",3452,3489);
$z[14][4]['filename']="footer.htm";

?>