<?php
$z[0]=Array("field","",79,98);
$z[0][4]['name']="title";
$z[1]=Array("global","",99,125);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",166,195);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",235,293);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",771,806);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",5738,5775);
$z[5][4]['filename']="footer.htm";

?>