<?php
$z[0]=Array("arcurl","",43,58);
$z[1]=Array("title","",67,81);
$z[2]=Array("picname","",119,135);
$z[3]=Array("title","",190,204);
$z[4]=Array("arcurl","",271,286);
$z[5]=Array("title","",295,309);
$z[6]=Array("title","",329,343);
$z[7]=Array("typeurl","",399,415);
$z[8]=Array("typename","",417,434);
$z[9]=Array("phpurl","",486,501);
$z[10]=Array("id","",525,536);
$z[11]=Array("mid","",541,553);

?>