<?php
$z[0]=Array("global","",483,509);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",524,550);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("channel","\r\n            <li class=\"menu-item menu-item-type-taxonomy menu-item-object-category\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n            ",1095,1429);
$z[2][4]['type']="top";
$z[2][4]['row']="5";
$z[2][4]['currentstyle']="<li class='current-menu-item'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";

?>