<?php
$z[0]=Array("global","",79,105);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",149,179);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",216,243);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",1261,1287);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",1302,1328);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("channel","\r\n            <li class=\"menu-item menu-item-type-taxonomy menu-item-object-category\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n            ",1891,2213);
$z[5][4]['type']="top";
$z[5][4]['row']="5";
$z[5][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[6]=Array("arclist","\r\n      <li>\r\n        <div class=\"citem\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"> <img width=\"280\" height=\"180\" src=\"[field:picname/]\" class=\"attachment-post-thumbnail wp-post-image\" alt=\"[field:title/]\" /> <span></span> </a>\r\n          <div class=\"citemtxt\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n            <h4>[field:title/]</h4>\r\n            </a>\r\n            <p> <span><a href=\"[field:typeurl/]\">[field:typename/]</a></span> <em>\r\n              <label><script src=\"[field:phpurl/]/count.php?view=yes&aid=[field:id/]&mid=[field:mid/]\" type='text/javascript' language=\"javascript\"></script></label>\r\n              浏览</em> </p>\r\n          </div>\r\n        </div>\r\n      </li>\r\n      ",4583,5353);
$z[6][4]['typeid']="1";
$z[6][4]['row']="8";
$z[6][4]['titlelen']="32";
$z[7]=Array("arclist","\r\n      <li><img width=\"140\" height=\"50\" src=\"[field:picname/]\" class=\"attachment-post-thumbnail wp-post-image\" alt=\"c_logo15\" /></li>\r\n      ",8752,8944);
$z[7][4]['typeid']="13";
$z[7][4]['row']="15";
$z[8]=Array("include","",11823,11860);
$z[8][4]['filename']="footer.htm";

?>