<?php
$z[0]=Array("field","",79,98);
$z[0][4]['name']="title";
$z[1]=Array("global","",99,125);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",166,195);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",235,293);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",721,756);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n        <li class=\"cat-item\"><a href=\"[field:typeurl/]\">[field:typename/]</a> </li>\r\n        ",942,1195);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li class='current-cat'><a href='~typelink~' class='thisclass'>~typename~</a></li>";
$z[6]=Array("list","\r\n      <article>\r\n        <div class=\"citem\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"> <img src=\"[field:picname/]\" style=\"width: 280px;height: 180px;\" class=\"attachment-post-thumbnail wp-post-image\" alt=\"[field:title/]\" /> <span></span> </a>\r\n          <div class=\"citemtxt\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\" >\r\n            <h4>[field:title/]</h4>\r\n            </a>\r\n            <p><span><a href='[field:typeurl/]'>[field:typename/]</a></span><em>\r\n              <label>[field:click/]</label>\r\n              浏览</em> </p>\r\n          </div>\r\n        </div>\r\n      </article>\r\n      ",1374,2021);
$z[6][4]['pagesize']="12";
$z[7]=Array("include","",2073,2110);
$z[7][4]['filename']="footer.htm";

?>